server:
  port: 8080

turbo:
  data:
    platform: mongodb

spring:
  application:
    name: swork-backend
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://root:secretpassword@localhost:27017/swork_db?authSource=admin}
      auto-index-creation: false
  jackson:
    date-format: "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'"
    time-zone: UTC
    default-property-inclusion: non_null

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true

logging:
  level:
    root: INFO
    com.swork: DEBUG
    org.springframework.data.mongodb.core.ReactiveMongoTemplate: DEBUG
